config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'dashboard' => 'dashboard#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'welcome#index'
  devise_for :users
  resources :profiles, only:[:edit, :update, :show]
  resources :beneficiaries, only:[:edit, :update, :show]
  get '/account' => 'accounts#show', as: :account
  resources :addresses, only:[:edit, :update, :index]
  resources :transactions, only: [:index, :show, :new, :create] do
  	collection do
  		get :enquiry
  	end
  end
  resources :users, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%=link_to "Banking System", user_signed_in? ? dashboard_path : root_path, class: "navbar-brand"%>
    <div class="navbar-collapse collapse navbar-responsive-collapse ">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <%=link_to "#", class: "dropdown-toggle",'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false" do %>
              <%="Hi #{current_user.profile.first_name}"%> <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Account', account_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'View Profile', profile_path(@slug), :class => 'navbar-link' %></li>
              <li><%= link_to 'View Beneficiary', beneficiary_path(@slug), :class => 'navbar-link' %></li>
              <li><%= link_to 'View Address', addresses_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_side_bar.html.erb
<div class="col-lg-3">
  <div class="well sidebar-nav">
    <h3>Hi <%=current_user.profile.first_name.camelcase%></h3>
    <ul class="nav nav-list">
      <% if current_user.has_role? :customer %>
	      <li><%= link_to 'Withdraw / Deposit', new_transaction_path %></li>
	      <li><%= link_to 'Transactions History', transactions_path %></li>
	      <li><%= link_to 'Enquiry', enquiry_transactions_path %></li>
	    <% elsif current_user.has_role? :manager %>
	    	<li><%= link_to 'Users', users_path %></li>
	    <% end %>
    </ul>
  </div><!--/.well -->
</div><!--/span-->